# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: automl/service/automl/api/proto/forecasting.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from mlflow.protos.scalapb import scalapb_pb2 as scalapb_dot_scalapb__pb2
from mlflow.protos import databricks_pb2 as databricks__pb2
from databricks.automl.client.protos import common_pb2 as automl_dot_service_dot_automl_dot_api_dot_proto_dot_common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='automl/service/automl/api/proto/forecasting.proto',
  package='automl',
  syntax='proto2',
  serialized_options=b'\n\037com.databricks.api.proto.automl\240\001\001\342?\002\020\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n1automl/service/automl/api/proto/forecasting.proto\x12\x06\x61utoml\x1a\x15scalapb/scalapb.proto\x1a\x10\x64\x61tabricks.proto\x1a,automl/service/automl/api/proto/common.proto\"\xaf\x03\n\x11\x46orecastingParams\x12\x1d\n\ntable_name\x18\x01 \x01(\tR\ttableName\x12\x1d\n\ntarget_col\x18\x02 \x01(\tR\ttargetCol\x12\x19\n\x08time_col\x18\x03 \x01(\tR\x07timeCol\x12\x41\n\tfrequency\x18\x04 \x01(\x0e\x32#.automl.ForecastingParams.FrequencyR\tfrequency\x12\x18\n\x07horizon\x18\x05 \x01(\x03R\x07horizon\x12#\n\ridentity_cols\x18\x06 \x03(\tR\x0cidentityCols\x12%\n\x0eprimary_metric\x18\x07 \x01(\tR\rprimaryMetric\x12-\n\x12\x65xclude_frameworks\x18\x08 \x03(\tR\x11\x65xcludeFrameworks\x12\'\n\x0foutput_database\x18\t \x01(\tR\x0eoutputDatabase\"@\n\tFrequency\x12\n\n\x06SECOND\x10\x00\x12\n\n\x06MINUTE\x10\x01\x12\x08\n\x04HOUR\x10\x02\x12\x07\n\x03\x44\x41Y\x10\x03\x12\x08\n\x04WEEK\x10\x04\x42)\n\x1f\x63om.databricks.api.proto.automl\xa0\x01\x01\xe2?\x02\x10\x01'
  ,
  dependencies=[scalapb_dot_scalapb__pb2.DESCRIPTOR,databricks__pb2.DESCRIPTOR,automl_dot_service_dot_automl_dot_api_dot_proto_dot_common__pb2.DESCRIPTOR,])



_FORECASTINGPARAMS_FREQUENCY = _descriptor.EnumDescriptor(
  name='Frequency',
  full_name='automl.ForecastingParams.Frequency',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SECOND', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MINUTE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='HOUR', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DAY', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='WEEK', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=516,
  serialized_end=580,
)
_sym_db.RegisterEnumDescriptor(_FORECASTINGPARAMS_FREQUENCY)


_FORECASTINGPARAMS = _descriptor.Descriptor(
  name='ForecastingParams',
  full_name='automl.ForecastingParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='table_name', full_name='automl.ForecastingParams.table_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='tableName', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='target_col', full_name='automl.ForecastingParams.target_col', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='targetCol', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='time_col', full_name='automl.ForecastingParams.time_col', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='timeCol', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='frequency', full_name='automl.ForecastingParams.frequency', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='frequency', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='horizon', full_name='automl.ForecastingParams.horizon', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='horizon', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='identity_cols', full_name='automl.ForecastingParams.identity_cols', index=5,
      number=6, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='identityCols', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='primary_metric', full_name='automl.ForecastingParams.primary_metric', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='primaryMetric', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='exclude_frameworks', full_name='automl.ForecastingParams.exclude_frameworks', index=7,
      number=8, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='excludeFrameworks', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='output_database', full_name='automl.ForecastingParams.output_database', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='outputDatabase', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _FORECASTINGPARAMS_FREQUENCY,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=149,
  serialized_end=580,
)

_FORECASTINGPARAMS.fields_by_name['frequency'].enum_type = _FORECASTINGPARAMS_FREQUENCY
_FORECASTINGPARAMS_FREQUENCY.containing_type = _FORECASTINGPARAMS
DESCRIPTOR.message_types_by_name['ForecastingParams'] = _FORECASTINGPARAMS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ForecastingParams = _reflection.GeneratedProtocolMessageType('ForecastingParams', (_message.Message,), {
  'DESCRIPTOR' : _FORECASTINGPARAMS,
  '__module__' : 'automl.service.automl.api.proto.forecasting_pb2'
  # @@protoc_insertion_point(class_scope:automl.ForecastingParams)
  })
_sym_db.RegisterMessage(ForecastingParams)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
