# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: automl/service/automl/api/proto/regression.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from mlflow.protos.scalapb import scalapb_pb2 as scalapb_dot_scalapb__pb2
from mlflow.protos import databricks_pb2 as databricks__pb2
from databricks.automl.client.protos import common_pb2 as automl_dot_service_dot_automl_dot_api_dot_proto_dot_common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='automl/service/automl/api/proto/regression.proto',
  package='automl',
  syntax='proto2',
  serialized_options=b'\n\037com.databricks.api.proto.automl\240\001\001\342?\002\020\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n0automl/service/automl/api/proto/regression.proto\x12\x06\x61utoml\x1a\x15scalapb/scalapb.proto\x1a\x10\x64\x61tabricks.proto\x1a,automl/service/automl/api/proto/common.proto\"\x80\x03\n\x10RegressionParams\x12\x1d\n\ntable_name\x18\x01 \x01(\tR\ttableName\x12\x1d\n\ntarget_col\x18\x02 \x01(\tR\ttargetCol\x12\x19\n\x08time_col\x18\x03 \x01(\tR\x07timeCol\x12%\n\x0eprimary_metric\x18\x04 \x01(\tR\rprimaryMetric\x12-\n\x12\x65xclude_frameworks\x18\x05 \x03(\tR\x11\x65xcludeFrameworks\x12!\n\x0c\x65xclude_cols\x18\x06 \x03(\tR\x0b\x65xcludeCols\x12+\n\x08imputers\x18\x07 \x03(\x0b\x32\x0f.automl.ImputerR\x08imputers\x12\x1d\n\nmax_trials\x18\x08 \x01(\x03R\tmaxTrials\x12N\n\x15\x66\x65\x61ture_store_lookups\x18\t \x03(\x0b\x32\x1a.automl.FeatureStoreLookupR\x13\x66\x65\x61tureStoreLookupsB)\n\x1f\x63om.databricks.api.proto.automl\xa0\x01\x01\xe2?\x02\x10\x01'
  ,
  dependencies=[scalapb_dot_scalapb__pb2.DESCRIPTOR,databricks__pb2.DESCRIPTOR,automl_dot_service_dot_automl_dot_api_dot_proto_dot_common__pb2.DESCRIPTOR,])




_REGRESSIONPARAMS = _descriptor.Descriptor(
  name='RegressionParams',
  full_name='automl.RegressionParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='table_name', full_name='automl.RegressionParams.table_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='tableName', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='target_col', full_name='automl.RegressionParams.target_col', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='targetCol', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='time_col', full_name='automl.RegressionParams.time_col', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='timeCol', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='primary_metric', full_name='automl.RegressionParams.primary_metric', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='primaryMetric', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='exclude_frameworks', full_name='automl.RegressionParams.exclude_frameworks', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='excludeFrameworks', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='exclude_cols', full_name='automl.RegressionParams.exclude_cols', index=5,
      number=6, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='excludeCols', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='imputers', full_name='automl.RegressionParams.imputers', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='imputers', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='max_trials', full_name='automl.RegressionParams.max_trials', index=7,
      number=8, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='maxTrials', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='feature_store_lookups', full_name='automl.RegressionParams.feature_store_lookups', index=8,
      number=9, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='featureStoreLookups', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=148,
  serialized_end=532,
)

_REGRESSIONPARAMS.fields_by_name['imputers'].message_type = automl_dot_service_dot_automl_dot_api_dot_proto_dot_common__pb2._IMPUTER
_REGRESSIONPARAMS.fields_by_name['feature_store_lookups'].message_type = automl_dot_service_dot_automl_dot_api_dot_proto_dot_common__pb2._FEATURESTORELOOKUP
DESCRIPTOR.message_types_by_name['RegressionParams'] = _REGRESSIONPARAMS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RegressionParams = _reflection.GeneratedProtocolMessageType('RegressionParams', (_message.Message,), {
  'DESCRIPTOR' : _REGRESSIONPARAMS,
  '__module__' : 'automl.service.automl.api.proto.regression_pb2'
  # @@protoc_insertion_point(class_scope:automl.RegressionParams)
  })
_sym_db.RegisterMessage(RegressionParams)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
